Repository digital-academy-devops/terraform-gitops, pull requests merged in 2023-06, with the labels that each got.

#132 feat(states/system) add resources
  states/system/folder.tf
Labels: apply

#137 Add resource
  .github/CODEOWNERS
  states/system/folder.tf
Labels: apply

#134 feat(states/system) add resources
  .github/CODEOWNERS
  states/system/folder.tf
Labels: apply

#138 feat(states/zhportnyagin):create zhportnyagin
  states/zhportnyagin/.ttl
  states/zhportnyagin/outputs.tf
  states/zhportnyagin/setup.tf
  states/zhportnyagin/testinstance.tf
  states/zhportnyagin/yc.pub
Labels: apply

#133 feat(/states/system) addresource
  states/system/folder.tf
Labels: apply

#140 Resources
  states/nmelekhov/.ttl
  states/nmelekhov/github.rsa.pub
  states/nmelekhov/outputs.tf
  states/nmelekhov/setup.tf
  states/nmelekhov/testinstance.tf
Labels: apply

#143 Destroy states/nmelekhov
  states/nmelekhov/.destroy
  states/nmelekhov/.expires_at
Labels: destroy, expired

#142 Destroy states/zhportnyagin
  states/zhportnyagin/.destroy
  states/zhportnyagin/.expires_at
Labels: destroy, expired

#141 Resourses
  .github/CODEOWNERS
  states/aprokopev/.expires_at
  states/aprokopev/.ttl
  states/aprokopev/git.pub
  states/aprokopev/outputs.tf
  states/aprokopev/setup.tf
  states/aprokopev/testinstance.tf
Labels: apply

#144 create folder kondratev
  states/system/folder.tf
Labels: apply

#126 add task terraform
  states/Ghost19/.destroy
  states/Ghost19/.ttl
  states/Ghost19/elb.tf
  states/Ghost19/outputs.tf
  states/Ghost19/setup.tf
  states/Ghost19/testinstance.tf
  states/Ghost19/yc.pub
Labels: destroy

#147 Destroy states/kondratev
  states/kondratev/.destroy
  states/kondratev/.expires_at
Labels: destroy, expired

#148 Destroy states/aprokopev
  states/aprokopev/.destroy
  states/aprokopev/.expires_at
Labels: destroy, expired

#139 create minerva45
  states/system/folder.tf
Labels: apply

#149 fix(states/system): downcase names for MedianikZakhar folder
  states/system/folder.tf
Labels: apply

#150 add folder medianikzakhar
  .github/CODEOWNERS
  states/medianikzakhar/.ttl
  states/medianikzakhar/outputs.tf
  states/medianikzakhar/setup.tf
  states/medianikzakhar/testinstance.tf
  states/medianikzakhar/yc.pub
Labels: apply

#151 create-folder
  states/system/folder.tf
Labels: apply

#152 create-states
  states/Ghost19/.destroy
  states/Ghost19/.ttl
  states/Ghost19/setup.tf
Labels: apply

#154 Destroy states/Ghost19
  states/Ghost19/.destroy
  states/Ghost19/.expires_at
Labels: destroy, expired

#156 create resources
  states/system/folder.tf
Labels: apply

#155 add folder
  states/system/folder.tf
Labels: apply

#161 fix folder
  states/system/folder.tf
Labels: apply

#162 add states
  states/maksimlyubomsky/.ttl
  states/maksimlyubomsky/outputs.tf
  states/maksimlyubomsky/setup.tf
  states/maksimlyubomsky/testinstance.tf
  states/maksimlyubomsky/yc.pub
Labels: apply

#157 feat(/state/system): add folder panaev
  states/system/folder.tf
Labels: apply

#167 feat(/states/ipanaev): create ipanaev
  .github/CODEOWNERS
  states/ipanaev/.ttl
  states/ipanaev/id_rsa.pub
  states/ipanaev/outputs.tf
  states/ipanaev/setup.tf
  states/ipanaev/testinstance.tf
Labels: apply

#171 feat(states/system): add folder for dbaigozova
  .github/CODEOWNERS
  states/system/folder.tf
Labels: apply

#172 feat(states/dbaigozova): create resources
  states/dbaigozova/.ttl
  states/dbaigozova/elb.tf
  states/dbaigozova/mykey.pub
  states/dbaigozova/outputs.tf
  states/dbaigozova/setup.tf
  states/dbaigozova/testinstance.tf
Labels: apply

#173 Destroy states/dbaigozova
  states/dbaigozova/.destroy
  states/dbaigozova/.expires_at
Labels: destroy, expired
