Repository digital-academy-devops/terraform-gitops, pull requests merged in 2023-02, with the labels that each got.

#6 recreate mostashkin
  states/mostashkin/.destroy
  states/mostashkin/.expires_at
Labels: apply

#7 .destroy state/mostashkin
  states/mostashkin/.destroy
Labels: destroy

#13 Delete .destroy
  states/mostashkin/.destroy
  states/mostashkin/.expires_at
Labels: apply

#17 create folder mostashkin
  states/system/folder.tf
Labels: apply

#19 tune branch protection rule
  states/system/github.tf
Labels: apply

#18 create state/mostashkin
  .github/CODEOWNERS
  states/mostashkin/.ttl
  states/mostashkin/setup.tf
  states/mostashkin/testinstance.tf
  states/mostashkin/yc.pub
Labels: apply

#20 use repo key to get checks run on expiration PRs
  .github/workflows/expire.yaml
Labels: apply

#21 Destroy states/mostashkin
  states/mostashkin/.destroy
  states/mostashkin/.expires_at
Labels: destroy, expired

#22 Readme
  README.md
  states/README.md
Labels: apply

#23 add ychacarr to approvers
  states/system/github.tf
Labels: apply

#24 name tf steps, rm .destroy on apply
  .github/workflows/terraform.yaml
Labels: apply

#26 feat(states/mostashkin): add outputs
  states/mostashkin/outputs.tf
Labels: apply

#27 feat(states/system): add mostashkin2
  states/system/folder.tf
Labels: apply

#28 feat(states/mostashkin2): create mostashkin2
  .github/CODEOWNERS
  states/mostashkin2/.ttl
  states/mostashkin2/outputs.tf
  states/mostashkin2/setup.tf
  states/mostashkin2/testinstance.pub
  states/mostashkin2/testinstance.tf
Labels: apply

#29 chore(states/mostashkin): destroy
  states/mostashkin/.destroy
Labels: destroy

#30 feat(states/system): export default network subnets
  states/system/network.tf
  states/system/outputs.tf
Labels: apply

#31 fix(states/mostashkin2): use default subnet
  states/mostashkin2/testinstance.tf
Labels: apply

#32 fix(states/mostashkin2): use subnet from zone a
  states/mostashkin2/testinstance.tf
Labels: apply

#35 chore(states/system): remove mostashkin2
  states/system/folder.tf
Labels: apply

#40 feat(states/system): add robonen folder
  states/system/folder.tf
Labels: apply

#37 feat(states/system): add glebedev
  states/system/folder.tf
Labels: apply

#41 chore(states/mostashkin): add pubkey
  states/mostashkin/yc.pub
Labels: apply

#43 feat(states/mostashkin): add elb
  states/mostashkin/elb.tf
  states/mostashkin/outputs.tf
  states/mostashkin/testinstance.tf
Labels: apply

#44 feat(states/system): add load-balancer.viewer for terraform-viewer
  states/system/sa.tf
Labels: apply
