Repository digital-academy-devops/terraform-gitops, pull requests merged in 2023-05, with the labels that each got.

#96 feat(states/system): add eostrovatikova
  states/system/folder.tf
Labels: apply

#97 feat(states/eostrovatikova): create eostrovatikova
  .github/CODEOWNERS
  states/eostrovatikova/.ttl
  states/eostrovatikova/outputs.tf
  states/eostrovatikova/setup.tf
  states/eostrovatikova/testinstance.tf
  states/eostrovatikova/yc.pub
Labels: apply

#98 Destroy states/eostrovatikova
  states/eostrovatikova/.destroy
  states/eostrovatikova/.expires_at
Labels: destroy, expired

#99 feat(states/system): add alin
  states/system/folder.tf
Labels: apply

#105 Alin create resourses
  .github/CODEOWNERS
  states/alin/.ttl
  states/alin/outputs.tf
  states/alin/setup.tf
  states/alin/testinstance.tf
  states/alin/yc.pub
Labels: apply

#106 Destroy states/alin
  states/alin/.destroy
  states/alin/.expires_at
Labels: destroy, expired

#109 create folder mulenokv
  states/system/folder.tf
Labels: apply

#108 Update folder.tf
  states/system/folder.tf
Labels: apply

#112 feat(states/hzhuikov): create resources and add codeowners
  .github/CODEOWNERS
  states/hzhuikov/.ttl
  states/hzhuikov/elb.tf
  states/hzhuikov/mykey2.pub
  states/hzhuikov/outputs.tf
  states/hzhuikov/setup.tf
  states/hzhuikov/testinstance.tf
Labels: apply

#116 feat(system/folder): add resource + output
  states/system/folder.tf
Labels: apply

#117 feat(states/shpagin): create shpagin
  .github/CODEOWNERS
  states/shpagin/.ttl
  states/shpagin/outputs.tf
  states/shpagin/setup.tf
  states/shpagin/sshkey.pub
  states/shpagin/testinstance.tf
Labels: apply

#118 feat(states/common): common k8s cluster group max size 10
  states/common/k8s.tf
Labels: apply

#119 chore(states/shpagin): destroy
  states/shpagin/.destroy
Labels: destroy

#120 Destroy states/shpagin
  states/shpagin/.destroy
  states/shpagin/.expires_at
Labels: destroy, expired

#115 feat: add resource in folder.tf
  states/system/folder.tf
Labels: apply

#121 feat(states/sheverev): create sheverev
  states/sheverev/.ttl
  states/sheverev/key.pub
  states/sheverev/outputs.tf
  states/sheverev/setup.tf
  states/sheverev/testinstance.tf
Labels: apply

#123 feat(states/system): add abekrenev
  states/system/folder.tf
Labels: apply

#124 feat(states/abekrenev): create abekrenev state
  .github/CODEOWNERS
  states/abekrenev/.ttl
  states/abekrenev/outputs.tf
  states/abekrenev/setup.tf
  states/abekrenev/ssh_access_key.pub
  states/abekrenev/testinstance.tf
Labels: apply

#128 feat(states/sysytem): add idenisov
  states/system/folder.tf
Labels: apply

#127 Destroy states/abekrenev
  states/abekrenev/.destroy
  states/abekrenev/.expires_at
Labels: destroy, expired
